name: 'Puah Image to ECR'
description: 'todo'
author: 'Keboola'
inputs: 
  vendor:
    description: 'Vendor'
    required: true
  app_id:
    description: 'App'
    required: true
  username:
    description: 'Username'
    required: true
  password:
    description: 'Password'
    required: true
  tag:
    description: 'Tag'
    required: true
  source_image:
    description: 'Image'
    required: true
  push_latest:
    description: 'Image'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vendor }}
    - ${{ inputs.app_id }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.tag }}
    - ${{ inputs.source_image }}
    - ${{ inputs.push_latest }}
